# опис налаштувань контенерив(сервиси)

services:
  # name servese1
  rand-num1:
    #як зтворити образ
    image: rand-num   #назва образу, якщо иснуе то нова не створюеться
    build: .        #шлях до докер файлу (. папка гле мы сейчас работаем)

    #налаштування
    environment:
      START_RANGE: 0
      END_RANGE: 10

      # читання енв файла
    env_file:
      - .env

    #сервис2

  rand-num2:
    #як зтворити образ
    image: rand-num   #назва образу
    build: .        #шлях до докер файлу (. папка гле мы сейчас работаем)

    #налаштування
    environment:
      START_RANGE: -100
      END_RANGE: -50

      # читання енв файла
    env_file:
      - .env


  rand-num3:
    #як зтворити образ
    image: rand-num   #назва образу
    build: .        #шлях до докер файлу (. папка гле мы сейчас работаем)

    #налаштування
    environment:
      START_RANGE: 1000
      END_RANGE: 2000

      # читання енв файла
    env_file:
      - .env
