services:
  app1:
    #як зтворити образ
    image: rand-line  #назва образу, якщо иснуе то нова не створюеться
    build: .        #шлях до докер файлу (. папка гле мы сейчас работаем)

    #налаштування
    environment:
      SYMBOL: "-"
      MIN_LEN: 0
      MAX_LEN: 10
      DELAY: 2

      # читання енв файла
    env_file:
      - .env

  app2:
    #як зтворити образ
    image: rand-line  #назва образу, якщо иснуе то нова не створюеться
    build: .        #шлях до докер файлу (. папка гле мы сейчас работаем)

    #налаштування
    environment:
      SYMBOL: "*"
      MIN_LEN: 10
      MAX_LEN: 20
      DELAY: 4

      # читання енв файла
    env_file:
      - .env


  app3:
    #як зтворити образ
    image: rand-line  #назва образу, якщо иснуе то нова не створюеться
    build: .        #шлях до докер файлу (. папка гле мы сейчас работаем)

    #налаштування
    environment:
      SYMBOL: "%"
      MIN_LEN: 20
      MAX_LEN: 30
      DELAY: 6

      # читання енв файла
    env_file:
      - .env
